apiVersion: apps/v1
kind: Deployment
metadata: 
  name: front-deploy
  labels:
    flower: rose
  namespace: 2tapp
spec:
  selector:
    matchLabels:
      flower: rose
  replicas: 2
  template:
    metadata: 
      name: fron-container
      labels:
        flower: node
    spec:
      containers: 
        - name: my-container
	  image: trainwithshubham/flaskapp:latest
          ports:
	    - containerports: 8000
